apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookhub
spec:
  selector:
    matchLabels:
      app: bookhub
  template:
    metadata:
      labels:
        app: bookhub
    spec:
      containers:
      - name: bookhub
        image: registry.access.redhat.com/ubi8/nodejs-18
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"